# Generated by Django 2.2.6 on 2020-05-19 19:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=130)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('author', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='images/')),
                ('time', models.DateTimeField(blank=True)),
                ('slug', models.CharField(max_length=255)),
            ],
        ),
    ]
