# Generated by Django 2.2.6 on 2020-05-19 20:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='msg',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
