# Generated by Django 2.2.6 on 2020-05-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_about_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactService',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HeadQuater',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=20)),
                ('Street', models.CharField(max_length=100)),
                ('pincode_city_country', models.CharField(max_length=75)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='IndiaOffice',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=20)),
                ('Street', models.CharField(max_length=100)),
                ('pincode_city_country', models.CharField(max_length=75)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
