# Generated by Django 2.2.6 on 2020-05-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_contactservice_headquater_indiaoffice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactservice',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='headquater',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='indiaoffice',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
