# Generated by Django 2.2.6 on 2020-05-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20200521_1753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeadQuater',
            new_name='HeadOffice',
        ),
    ]
